In [12]:
#Standard Scaler syntax
# from sklearn.preprocessing import StandardScaler
# scaler = StandardScaler()
# X_scaled = scaler.fit_transform(X)

In [13]:
# MimMax Scaling
# from sklearn.preprocessing import MinMaxScaler
# scaler = MinMaxScaler()
# X_scaled = scaler.fit_transform()

In [14]:
# Splitting data
# from sklearn.model_selection import train_test_split

In [15]:
# actual how all the feature selection works
import pandas as pd
from sklearn.preprocessing import StandardScaler , MinMaxScaler
from sklearn.model_selection import train_test_split

In [16]:
# making the dataset
data = {
    "StudyHours": [1,2,3,4,5],
    "TestScore": [40,50,60,70,80]

}
df = pd.DataFrame(data)

In [17]:
#standard Scaler
Scaler = StandardScaler()
df_Scaled = Scaler.fit_transform(df)
pd.DataFrame(df_Scaled, columns=["StudyHours", "TestScore"])

   StudyHours  TestScore
0   -1.414214  -1.414214
1   -0.707107  -0.707107
2    0.000000   0.000000
3    0.707107   0.707107
4    1.414214   1.414214

In [18]:
# minmax scaler
minmaxScaler = MinMaxScaler()
minmax_Scaled = minmaxScaler.fit_transform(df)
pd.DataFrame(minmax_Scaled , columns=["StudyHours", "TestScore"])

   StudyHours  TestScore
0        0.00       0.00
1        0.25       0.25
2        0.50       0.50
3        0.75       0.75
4        1.00       1.00

In [22]:
# train test split

X = df[["StudyHours"]]
y =df[["TestScore"]]

X_train, X_test , y_train, y_test = train_test_split(X , y , test_size=0.2, random_state=42)

print("Training Data")
print(X_train)
print(y_train)



print("Testing Data")
print(X_test)

Training Data
   StudyHours
4           5
2           3
0           1
3           4
   TestScore
4         80
2         60
0         40
3         70
Testing Data
   StudyHours
1           2