In [1]:
import pandas as pd

In [3]:
data = {
    'Name':['Ram','Sital','Shyam','Gyan','Man'],
    'Age':[23,None, 54, 23, None],
    'Salary': [1344, 2000, 3000, None, None]
}

In [4]:
# creating the dataframe
df = pd.DataFrame(data)
print("original dataframe")
df

original dataframe

    Name   Age  Salary
0    Ram  23.0  1344.0
1  Sital   NaN  2000.0
2  Shyam  54.0  3000.0
3   Gyan  23.0     NaN
4    Man   NaN     NaN

In [5]:
# to find the total number of the missing values in the each column
df.isnull().sum()

Name      0
Age       2
Salary    2
dtype: int64

In [6]:
# to delete the missing values column
del_df = df.dropna()
del_df

    Name   Age  Salary
0    Ram  23.0  1344.0
2  Shyam  54.0  3000.0

In [8]:
# no filling the value
df['Age'].fillna(df["Age"].mean(), inplace=True)
df['Salary'].fillna(df["Salary"].mean() , inplace=True)
df

C:\Users\Sital\AppData\Local\Temp\ipykernel_9364\228418998.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(df["Age"].mean(), inplace=True)
C:\Users\Sital\AppData\Local\Temp\ipykernel_9364\228418998.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Salary'].fillna(df["Salary"].mean() , inplace=True)

    Name        Age       Salary
0    Ram  23.000000  1344.000000
1  Sital  33.333333  2000.000000
2  Shyam  54.000000  3000.000000
3   Gyan  23.000000  2114.666667
4    Man  33.333333  2114.666667